# Copyright 2022 Akretion - Raphaël Valyi <raphael.valyi@akretion.com>
# License LGPL-3.0 or later (https://www.gnu.org/licenses/lgpl-3.0.en.html).
# Generated by https://github.com/akretion/xsdata-odoo

"""
STRUCTURE SPED ECD

<BLOCO 0>

  - 0007 OUTRAS INSCRIÇÕES CADASTRAIS DA PESSOA JURÍDICA

  - 0020 ESCRITURAÇÃO CONTÁBIL DESCENTRALIZADA

  - 0035 IDENTIFICAÇÃO DAS SCP

  - 0150 TABELA DE CADASTRO DO PARTICIPANTE
    ≡ 0180 identificação do relacionamento com o participante

<BLOCO I>

  - I010 IDENTIFICAÇÃO DA ESCRITURAÇÃO CONTÁBIL
    ≡ I012 livros auxiliares ao diário
      ≡ I015 
    ≡ I020 campos adicionais
    ≡ I030 termo de abertura
    ≡ I050 plano de contas
      ≡ I051 
      ≡ I052 
      ≡ I053 
    ≡ I075 tabela de histórico padronizado
    ≡ I100 centro de custos
    ≡ I150 saldos periódicos – identificação do período
      ≡ I155 
        ≡ I157 
    ≡ I200 lançamento contábil
      ≡ I250 
    ≡ I300 balancetes diários – identificação da data
      ≡ I310 
    ≡ I350 SALDOS DAS CONTAS DE RESULTADO ANTES DO ...
      ≡ I355 
    ≡ I500 PARÂMETROS DE IMPRESSÃO/VISUALIZAÇÃO DO ...
    ≡ I510 DEFINIÇÃO DOS CAMPOS DO LIVRO RAZÃO AUXI...
    ≡ I550 DETALHES DO LIVRO RAZÃO AUXILIAR COM LEI...
      ≡ I555 

<BLOCO J>

  - J005 DEMONSTRAÇÕES CONTÁBEIS
    ≡ J100 balanço patrimonial
    ≡ J150 demonstração do resultado do exercício
    ≡ J210 de ou demonstração lucros prejuízos acumulados do
      ≡ J215 
    ≡ J800 outras informações
    ≡ J801 termo de verificação para fins de substituição da ecd

  - J900 TERMO DE ENCERRAMENTO
    ≡ J930 signatários da escrituração
    ≡ J932 SIGNATÁRIOS DO TERMO DE VERIFICAÇÃO PARA...
    ≡ J935 identificação dos auditores independentes

<BLOCO K>

  - K030 PERÍODO DA ESCRITURAÇÃO CONTÁBIL CONSOLIDADA
    ≡ K100 relação das empresas consolidadas
      ≡ K110 
        ≡ K115 

  - K200 PLANO DE CONTAS CONSOLIDADO
    ≡ K210 MAPEAMENTO PARA O PLANO DE CONTAS DAS EM...
    ≡ K300 saldos das contas consolidadas
      ≡ K310 
        ≡ K315 

<BLOCO 9>

  - 9900 REGISTROS DO ARQUIVO
"""

import textwrap
from odoo import fields, models


class Registro0007(models.Model):
    "OUTRAS INSCRIÇÕES CADASTRAIS DA PESSOA JURÍDICA"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.0007"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "Registro0007"

    COD_ENT_REF = fields.Char(
        string="REF",
        required=True,
        help=(
            "Código da instituição responsável pela administração do cadastro "
            "(conforme tabela publicada pelo Sped)."
        ),
    )

    COD_INSCR = fields.Char(
        string="INSCR",
        help=(
            "Código cadastral da pessoa jurídica na instituição identificada "
            "no campo 02."
        ),
    )


class Registro0020(models.Model):
    "ESCRITURAÇÃO CONTÁBIL DESCENTRALIZADA"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.0020"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "Registro0020"

    IND_DEC = fields.Integer(
        string="Indicador de descentralização: 0 – Escrituração da matriz",
        required=True,
        help=(
            "Indicador de descentralização: 0 – Escrituração da matriz. 1 – "
            "Escrituração da filial."
        ),
    )

    CNPJ = fields.Integer(
        string="CNPJ",
        required=True,
        help=(
            "Número de inscrição da pessoa jurídica no CNPJ da matriz ou da " "filial."
        ),
    )

    UF = fields.Char(
        string="Sigla da unidade da federação da matriz ou da filial", required=True
    )

    IE = fields.Char(string="Inscrição estadual da matriz ou da filial")

    COD_MUN = fields.Integer(
        string="Código do município do domicílio da matriz ou da filial"
    )

    IM = fields.Char(string="Número de Inscrição Municipal da matriz ou da filial")

    NIRE = fields.Integer(
        string="NIRE",
        help=(
            "Número de Identificação do Registro de Empresas da matriz ou da "
            "filial na Junta Comercial."
        ),
    )


class Registro0035(models.Model):
    "IDENTIFICAÇÃO DAS SCP"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.0035"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "Registro0035"


class Registro0150(models.Model):
    "TABELA DE CADASTRO DO PARTICIPANTE"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.0150"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "Registro0150"

    COD_PART = fields.Char(
        string="PART",
        required=True,
        help=(
            "Código de identificação do participante no arquivo criado pela "
            "própria pessoa jurídica."
        ),
    )

    NOME = fields.Char(
        string="Nome pessoal ou empresarial do participante", required=True
    )

    COD_PAIS = fields.Integer(
        string="Código do país do participante",
        required=True,
        help=(
            "Código do país do participante, conforme a tabela do Banco "
            "Central do Brasil."
        ),
    )

    CNPJ = fields.Integer(string="CNPJ do participante")

    CPF = fields.Integer(string="CPF do participante")

    NIT = fields.Integer(
        string="Número de Identificação do Trabalhador",
        help="Número de Identificação do Trabalhador, Pis, Pasep, SUS.",
    )

    UF = fields.Char(string="Sigla da unidade da federação do participante")

    IE = fields.Char(string="Inscrição Estadual do participante")

    IE_ST = fields.Char(
        string="ST",
        help=(
            "Inscrição Estadual do participante na unidade da federação do "
            "destinatário, na condição de contribuinte substituto."
        ),
    )

    COD_MUN = fields.Integer(
        string="Código do município",
        help="Código do município, conforme a tabela do IBGE.",
    )

    IM = fields.Char(string="Inscrição Municipal do participante")

    SUFRAMA = fields.Char(string="Número de inscrição do participante na Suframa")

    reg_0180_ids = fields.One2many(
        "l10n_br_sped.ecd.1.0180",
        "reg_0180_ids_Registro0150_id",
        string="IDENTIFICAÇÃO DO RELACIONAMENTO COM O PARTICIPANTE",
    )


class Registro0180(models.Model):
    "IDENTIFICAÇÃO DO RELACIONAMENTO COM O PARTICIPANTE"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.0180"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "Registro0180"

    COD_REL = fields.Integer(
        string="REL",
        required=True,
        help=("Código do relacionamento conforme tabela publicada pelo Sped."),
    )

    DT_INI_REL = fields.Date(string="Data do início do relacionamento", required=True)

    DT_FIN_REL = fields.Date(string="Data do término do relacionamento")

    reg_0180_ids_Registro0150_id = fields.Many2one(
        comodel_name="l10n_br_sped.ecd.1.0150",
        string="TABELA DE CADASTRO DO PARTICIPANTE",
        required=True,
    )


class RegistroI010(models.Model):
    "IDENTIFICAÇÃO DA ESCRITURAÇÃO CONTÁBIL"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.I010"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "RegistroI010"

    IND_ESC = fields.Char(
        string="G R A B Z Indicador da forma de escrituração contábil",
        required=True,
        help=(
            "G R A B Z Indicador da forma de escrituração contábil: - Livro "
            "Diário (Completo sem escrituração auxiliar). - Livro Diário com "
            "Escrituração Resumida (com escrituração auxiliar). - Livro Diário"
            " Auxiliar ao Diário com Escrituração Resumida. - Livro Balancetes"
            " Diários e Balanços. – Razão Auxiliar (Livro Contábil Auxiliar "
            "conforme leiaute definido nos registros I500 a I555)."
        ),
    )

    COD_VER_LC = fields.Char(
        string="Código da Versão do Leiaute Contábil", required=True
    )

    reg_I012_ids = fields.One2many(
        "l10n_br_sped.ecd.1.I012",
        "reg_I012_ids_RegistroI010_id",
        string="LIVROS AUXILIARES AO DIÁRIO",
    )

    reg_I020_ids = fields.One2many(
        "l10n_br_sped.ecd.1.I020",
        "reg_I020_ids_RegistroI010_id",
        string="CAMPOS ADICIONAIS",
    )

    reg_I030_ids = fields.One2many(
        "l10n_br_sped.ecd.1.I030",
        "reg_I030_ids_RegistroI010_id",
        string="TERMO DE ABERTURA",
    )

    reg_I050_ids = fields.One2many(
        "l10n_br_sped.ecd.1.I050",
        "reg_I050_ids_RegistroI010_id",
        string="PLANO DE CONTAS",
    )

    reg_I075_ids = fields.One2many(
        "l10n_br_sped.ecd.1.I075",
        "reg_I075_ids_RegistroI010_id",
        string="TABELA DE HISTÓRICO PADRONIZADO",
    )

    reg_I100_ids = fields.One2many(
        "l10n_br_sped.ecd.1.I100",
        "reg_I100_ids_RegistroI010_id",
        string="CENTRO DE CUSTOS",
    )

    reg_I150_ids = fields.One2many(
        "l10n_br_sped.ecd.1.I150",
        "reg_I150_ids_RegistroI010_id",
        string="SALDOS PERIÓDICOS – IDENTIFICAÇÃO DO PERÍODO",
    )

    reg_I200_ids = fields.One2many(
        "l10n_br_sped.ecd.1.I200",
        "reg_I200_ids_RegistroI010_id",
        string="LANÇAMENTO CONTÁBIL",
    )

    reg_I300_ids = fields.One2many(
        "l10n_br_sped.ecd.1.I300",
        "reg_I300_ids_RegistroI010_id",
        string="BALANCETES DIÁRIOS – IDENTIFICAÇÃO DA DATA",
    )

    reg_I350_ids = fields.One2many(
        "l10n_br_sped.ecd.1.I350",
        "reg_I350_ids_RegistroI010_id",
        string="ids",
        help=(
            "SALDOS DAS CONTAS DE RESULTADO ANTES DO ENCERRAMENTO – "
            "IDENTIFICAÇÃO DA DATA"
        ),
    )

    reg_I500_ids = fields.One2many(
        "l10n_br_sped.ecd.1.I500",
        "reg_I500_ids_RegistroI010_id",
        string="ids (reg_I500_ids)",
        help=(
            "PARÂMETROS DE IMPRESSÃO/VISUALIZAÇÃO DO LIVRO RAZÃO AUXILIAR COM "
            "LEIAUTE PARAMETRIZÁVEL"
        ),
    )

    reg_I510_ids = fields.One2many(
        "l10n_br_sped.ecd.1.I510",
        "reg_I510_ids_RegistroI010_id",
        string="ids (reg_I510_ids)",
        help=(
            "DEFINIÇÃO DOS CAMPOS DO LIVRO RAZÃO AUXILIAR COM LEIAUTE " "PARAMETRIZÁVEL"
        ),
    )

    reg_I550_ids = fields.One2many(
        "l10n_br_sped.ecd.1.I550",
        "reg_I550_ids_RegistroI010_id",
        string="ids (reg_I550_ids)",
        help="DETALHES DO LIVRO RAZÃO AUXILIAR COM LEIAUTE PARAMETRIZÁVEL",
    )


class RegistroI012(models.Model):
    "LIVROS AUXILIARES AO DIÁRIO"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.I012"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "RegistroI012"

    NUM_ORD = fields.Integer(
        string="Número de ordem do instrumento associado", required=True
    )

    NAT_LIVR = fields.Char(
        string="LIVR",
        required=True,
        help=(
            "Natureza do livro associado; finalidade a que se destina o " "instrumento."
        ),
    )

    TIPO = fields.Integer(
        string="Tipo de escrituração do livro associado: 0 – digital",
        required=True,
        help=(
            "Tipo de escrituração do livro associado: 0 – digital (incluído no"
            " Sped). 1 – outros."
        ),
    )

    COD_HASH_AUX = fields.Char(
        string="AUX",
        help=(
            "Código Hash do arquivo correspondente ao livro auxiliar utilizado"
            " na assinatura digital."
        ),
    )

    reg_I012_ids_RegistroI010_id = fields.Many2one(
        comodel_name="l10n_br_sped.ecd.1.I010",
        string="IDENTIFICAÇÃO DA ESCRITURAÇÃO CONTÁBIL",
        required=True,
    )

    reg_I015_ids = fields.One2many(
        "l10n_br_sped.ecd.1.I015",
        "reg_I015_ids_RegistroI012_id",
        string="ids",
        help=(
            "IDENTIFICAÇÃO DAS CONTAS DA ESCRITURAÇÃO RESUMIDA A QUE SE REFERE"
            " A ESCRITURAÇÃO AUXILIAR"
        ),
    )


class RegistroI015(models.Model):
    """IDENTIFICAÇÃO DAS CONTAS DA ESCRITURAÇÃO RESUMIDA A QUE SE REFERE A
    ESCRITURAÇÃO AUXILIAR"""

    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.I015"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "RegistroI015"

    COD_CTA_RES = fields.Char(
        string="RES",
        required=True,
        help=(
            "Código da(s) conta(s) analítica(s) do Livro Diário com "
            "Escrituração Resumida (R) que recebe os lançamentos globais (deve"
            " corresponder a uma conta sintética no livro auxiliar)."
        ),
    )

    reg_I015_ids_RegistroI012_id = fields.Many2one(
        comodel_name="l10n_br_sped.ecd.1.I012",
        string="LIVROS AUXILIARES AO DIÁRIO",
        required=True,
    )


class RegistroI020(models.Model):
    "CAMPOS ADICIONAIS"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.I020"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "RegistroI020"

    REG_COD = fields.Char(
        string="Código do registro que recepciona o campo adicional", required=True
    )

    NUM_AD = fields.Integer(
        string="Número sequencial do campo adicional", required=True
    )

    CAMPO = fields.Char(string="Nome do campo adicional", required=True)

    DESCRIÇÃO = fields.Char(string="Descrição do campo adicional")

    TIPO = fields.Char(
        string="C Indicação do tipo de dado",
        required=True,
        help=(
            "C Indicação do tipo de dado (N: numérico; C: caractere). N: "
            "numérico - campos adicionais que conterão informações de valores "
            "em espécie (moeda), com duas decimais. : caractere - campos "
            "adicionais que conterão outras informações que não sejam valores "
            "em espécie (moeda), Exemplos: Códigos, CNPJ, CPF, etc."
        ),
    )

    IND_DC_INI_MF = fields.Char(
        string="MF",
        help=(
            "Indicador da situação do saldo inicial em moeda funcional: D - "
            "Devedor; C - Credor."
        ),
    )

    reg_I020_ids_RegistroI010_id = fields.Many2one(
        comodel_name="l10n_br_sped.ecd.1.I010",
        string="IDENTIFICAÇÃO DA ESCRITURAÇÃO CONTÁBIL",
        required=True,
    )


class RegistroI030(models.Model):
    "TERMO DE ABERTURA"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.I030"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "RegistroI030"

    DNRC_ABERT = fields.Char(
        string="Texto fixo contendo “TERMO DE ABERTURA”", required=True
    )

    NUM_ORD = fields.Integer(
        string="Número de ordem do instrumento de escrituração", required=True
    )

    NAT_LIVR = fields.Char(
        string="LIVR",
        required=True,
        help=("Natureza do livro; finalidade a que se destina o instrumento."),
    )

    QTD_LIN = fields.Integer(
        string="Quantidade total de linhas do arquivo digital", required=True
    )

    NOME = fields.Char(string="Nome empresarial", required=True)

    NIRE = fields.Integer(
        string="NIRE",
        help=("Número de Identificação do Registro de Empresas da Junta " "Comercial."),
    )

    CNPJ = fields.Integer(string="Número de inscrição no CNPJ", required=True)

    DT_ARQ = fields.Date(string="Data do arquivamento dos atos constitutivos")

    DT_ARQ_CONV = fields.Date(
        string="CONV",
        help=(
            "Data de arquivamento do ato de conversão de sociedade simples em "
            "sociedade empresária."
        ),
    )

    DESC_MUN = fields.Char(string="Município")

    DT_EX_SOCIAL = fields.Date(
        string="Data de encerramento do exercício social", required=True
    )

    reg_I030_ids_RegistroI010_id = fields.Many2one(
        comodel_name="l10n_br_sped.ecd.1.I010",
        string="IDENTIFICAÇÃO DA ESCRITURAÇÃO CONTÁBIL",
        required=True,
    )


class RegistroI050(models.Model):
    "PLANO DE CONTAS"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.I050"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "RegistroI050"

    DT_ALT = fields.Date(string="Data da inclusão/alteração", required=True)

    COD_NAT = fields.Char(
        string="Código da natureza da conta/grupo de contas",
        required=True,
        help=(
            "Código da natureza da conta/grupo de contas, conforme tabela "
            "publicada pelo Sped."
        ),
    )

    IND_CTA = fields.Char(
        string="Indicador do tipo de conta: S",
        required=True,
        help=(
            "Indicador do tipo de conta: S - Sintética (grupo de contas) A - "
            "Analítica (conta)"
        ),
    )

    NIVEL = fields.Integer(
        string="Nível da conta analítica/grupo de contas", required=True
    )

    COD_CTA = fields.Char(
        string="Código da conta analítica/grupo de contas", required=True
    )

    COD_CTA_SUP = fields.Char(
        string="SUP",
        help=(
            "Código da conta sintética /grupo de contas de nível imediatamente"
            " superior."
        ),
    )

    CTA = fields.Char(string="Nome da conta analítica/grupo de contas", required=True)

    reg_I050_ids_RegistroI010_id = fields.Many2one(
        comodel_name="l10n_br_sped.ecd.1.I010",
        string="IDENTIFICAÇÃO DA ESCRITURAÇÃO CONTÁBIL",
        required=True,
    )

    reg_I051_ids = fields.One2many(
        "l10n_br_sped.ecd.1.I051",
        "reg_I051_ids_RegistroI050_id",
        string="PLANO DE CONTAS REFERENCIAL",
    )

    reg_I052_ids = fields.One2many(
        "l10n_br_sped.ecd.1.I052",
        "reg_I052_ids_RegistroI050_id",
        string="INDICAÇÃO DOS CÓDIGOS DE AGLUTINAÇÃO",
    )

    reg_I053_ids = fields.One2many(
        "l10n_br_sped.ecd.1.I053",
        "reg_I053_ids_RegistroI050_id",
        string="SUBCONTAS CORRELATAS",
    )


class RegistroI051(models.Model):
    "PLANO DE CONTAS REFERENCIAL"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.I051"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "RegistroI051"

    COD_CCUS = fields.Char(string="Código do centro de custo")

    COD_CTA_REF = fields.Char(
        string="REF",
        required=True,
        help=(
            "Código da conta de acordo com o plano de contas referencial, "
            "conforme tabela publicada pelos órgãos indicados no campo "
            "COD_PLAN_REF do registro 0000."
        ),
    )

    reg_I051_ids_RegistroI050_id = fields.Many2one(
        comodel_name="l10n_br_sped.ecd.1.I050", string="PLANO DE CONTAS", required=True
    )


class RegistroI052(models.Model):
    "INDICAÇÃO DOS CÓDIGOS DE AGLUTINAÇÃO"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.I052"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "RegistroI052"

    COD_CCUS = fields.Char(string="Código do centro de custo")

    COD_AGL = fields.Char(
        string="AGL",
        required=True,
        help=(
            "Código de aglutinação utilizado nas demonstrações contábeis do "
            "bloco J (Somente para as contas analíticas)."
        ),
    )

    reg_I052_ids_RegistroI050_id = fields.Many2one(
        comodel_name="l10n_br_sped.ecd.1.I050", string="PLANO DE CONTAS", required=True
    )


class RegistroI053(models.Model):
    "SUBCONTAS CORRELATAS"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.I053"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "RegistroI053"

    COD_IDT = fields.Char(
        string="Código de identificação do grupo de conta",
        required=True,
        help="Código de identificação do grupo de conta- subconta(s)",
    )

    COD_CNT_CORR = fields.Char(
        string="Código da subconta correlata",
        required=True,
        help=(
            "Código da subconta correlata (deve estar no plano de contas e só "
            "pode estar relacionada a um único grupo)"
        ),
    )

    NAT_SUB_CNT = fields.Char(
        string="Natureza da subconta correlata",
        required=True,
        help=(
            "Natureza da subconta correlata (conforme tabela de natureza da "
            "subconta publicada no Sped )"
        ),
    )

    reg_I053_ids_RegistroI050_id = fields.Many2one(
        comodel_name="l10n_br_sped.ecd.1.I050", string="PLANO DE CONTAS", required=True
    )


class RegistroI075(models.Model):
    "TABELA DE HISTÓRICO PADRONIZADO"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.I075"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "RegistroI075"

    COD_HIST = fields.Char(string="Código do histórico padronizado", required=True)

    DESCR_HIST = fields.Char(string="Descrição do histórico padronizado", required=True)

    reg_I075_ids_RegistroI010_id = fields.Many2one(
        comodel_name="l10n_br_sped.ecd.1.I010",
        string="IDENTIFICAÇÃO DA ESCRITURAÇÃO CONTÁBIL",
        required=True,
    )


class RegistroI100(models.Model):
    "CENTRO DE CUSTOS"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.I100"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "RegistroI100"

    DT_ALT = fields.Date(string="Data da inclusão/alteração", required=True)

    COD_CCUS = fields.Char(string="Código do centro de custos", required=True)

    CCUS = fields.Char(string="Nome do centro de custos", required=True)

    reg_I100_ids_RegistroI010_id = fields.Many2one(
        comodel_name="l10n_br_sped.ecd.1.I010",
        string="IDENTIFICAÇÃO DA ESCRITURAÇÃO CONTÁBIL",
        required=True,
    )


class RegistroI150(models.Model):
    "SALDOS PERIÓDICOS – IDENTIFICAÇÃO DO PERÍODO"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.I150"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "RegistroI150"

    DT_INI = fields.Date(string="Data de início do período", required=True)

    DT_FIN = fields.Date(string="Data de fim do período", required=True)

    reg_I150_ids_RegistroI010_id = fields.Many2one(
        comodel_name="l10n_br_sped.ecd.1.I010",
        string="IDENTIFICAÇÃO DA ESCRITURAÇÃO CONTÁBIL",
        required=True,
    )

    reg_I155_ids = fields.One2many(
        "l10n_br_sped.ecd.1.I155",
        "reg_I155_ids_RegistroI150_id",
        string="DETALHES DOS SALDOS PERIÓDICOS",
    )


class RegistroI155(models.Model):
    "DETALHES DOS SALDOS PERIÓDICOS"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.I155"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "RegistroI155"

    COD_CTA = fields.Char(string="Código da conta analítica", required=True)

    COD_CCUS = fields.Char(string="Código do centro de custos")

    VL_SLD_INI = fields.Monetary(
        string="Valor do saldo inicial do período",
        required=True,
        xsd_type="TDec_1602",
        currency_field="brl_currency_id",
    )

    IND_DC_INI = fields.Char(
        string="Indicador da situação do saldo inicial: D",
        help=("Indicador da situação do saldo inicial: D - Devedor; C - Credor."),
    )

    VL_DEB = fields.Monetary(
        string="Valor total dos débitos do período",
        required=True,
        xsd_type="TDec_1602",
        currency_field="brl_currency_id",
    )

    VL_CRED = fields.Monetary(
        string="Valor total dos créditos do período",
        required=True,
        xsd_type="TDec_1602",
        currency_field="brl_currency_id",
    )

    VL_SLD_FIN = fields.Monetary(
        string="Valor do saldo final do período",
        required=True,
        xsd_type="TDec_1602",
        currency_field="brl_currency_id",
    )

    IND_DC_FIN = fields.Char(
        string="Indicador da situação do saldo final: D",
        help=("Indicador da situação do saldo final: D - Devedor; C - Credor."),
    )

    VL_SLD_INI_MF = fields.Monetary(
        string="Valor do saldo inicial do período em moeda funcional",
        xsd_type="TDec_1602",
        currency_field="brl_currency_id",
        help=(
            "Valor do saldo inicial do período em moeda funcional, convertido "
            "para reais."
        ),
    )

    IND_DC_INI_MF = fields.Char(
        string="MF",
        help=(
            "Indicador da situação do saldo inicial em moeda funcional: D - "
            "Devedor; C - Credor."
        ),
    )

    VL_DEB_MF = fields.Monetary(
        string="Valor total dos débitos do período em moeda funcional",
        xsd_type="TDec_1602",
        currency_field="brl_currency_id",
        help=(
            "Valor total dos débitos do período em moeda funcional, convertido"
            " para reais."
        ),
    )

    VL_CRED_MF = fields.Monetary(
        string="Valor total dos créditos do período em moeda funcional",
        xsd_type="TDec_1602",
        currency_field="brl_currency_id",
        help=(
            "Valor total dos créditos do período em moeda funcional, "
            "convertido para reais."
        ),
    )

    VL_SLD_FIN_MF = fields.Monetary(
        string="Valor do saldo final do período em moeda funcional",
        xsd_type="TDec_1602",
        currency_field="brl_currency_id",
        help=(
            "Valor do saldo final do período em moeda funcional, convertido "
            "para reais."
        ),
    )

    IND_DC_FIN_MF = fields.Char(
        string="Indicador da situação do saldo final em moeda funcional: D",
        help=(
            "Indicador da situação do saldo final em moeda funcional: D - "
            "Devedor; C - Credor."
        ),
    )

    reg_I155_ids_RegistroI150_id = fields.Many2one(
        comodel_name="l10n_br_sped.ecd.1.I150",
        string="SALDOS PERIÓDICOS – IDENTIFICAÇÃO DO PERÍODO",
        required=True,
    )

    reg_I157_ids = fields.One2many(
        "l10n_br_sped.ecd.1.I157",
        "reg_I157_ids_RegistroI155_id",
        string="TRANSFERÊNCIA DE SALDOS DO PLANO DE CONTAS ANTERIOR",
    )


class RegistroI157(models.Model):
    "TRANSFERÊNCIA DE SALDOS DO PLANO DE CONTAS ANTERIOR"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.I157"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "RegistroI157"

    COD_CTA = fields.Char(
        string="Código da conta analítica do plano de contas anterior", required=True
    )

    COD_CCUS = fields.Char(
        string="Código do centro de custos do plano de contas anterior"
    )

    VL_SLD_INI = fields.Monetary(
        string="Valor do saldo inicial do período",
        required=True,
        xsd_type="TDec_1602",
        currency_field="brl_currency_id",
    )

    IND_DC_INI = fields.Char(
        string="Indicador da situação do saldo inicial: D",
        help=("Indicador da situação do saldo inicial: D - Devedor; C - Credor."),
    )

    VL_SLD_INI_MF = fields.Monetary(
        string="Valor do saldo inicial do período em moeda funcional",
        xsd_type="TDec_1602",
        currency_field="brl_currency_id",
        help=(
            "Valor do saldo inicial do período em moeda funcional, convertido "
            "para reais."
        ),
    )

    IND_DC_INI_MF = fields.Char(
        string="MF",
        help=(
            "Indicador da situação do saldo inicial em moeda funcional: D - "
            "Devedor; C - Credor."
        ),
    )

    reg_I157_ids_RegistroI155_id = fields.Many2one(
        comodel_name="l10n_br_sped.ecd.1.I155",
        string="DETALHES DOS SALDOS PERIÓDICOS",
        required=True,
    )


class RegistroI200(models.Model):
    "LANÇAMENTO CONTÁBIL"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.I200"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "RegistroI200"

    NUM_LCTO = fields.Char(
        string="LCTO",
        required=True,
        help=("Número ou Código de identificação único do lançamento contábil."),
    )

    DT_LCTO = fields.Date(string="Data do lançamento", required=True)

    VL_LCTO = fields.Monetary(
        string="Valor do lançamento",
        required=True,
        xsd_type="TDec_1602",
        currency_field="brl_currency_id",
    )

    IND_LCTO = fields.Char(
        string="Indicador do tipo de lançamento: N",
        required=True,
        help=(
            "Indicador do tipo de lançamento: N - Lançamento normal (todos os "
            "lançamentos, exceto os de encerramento das contas de resultado); "
            "E - Lançamento de encerramento de contas de resultado. X – "
            "Lançamento extemporâneo."
        ),
    )

    DT_LCTO_EXT = fields.Date(
        string="EXT",
        help=(
            "O Data de ocorrência dos fatos objeto do lançamento extemporâneo."
            " bservação: Caso não seja possível precisar a data a que se "
            "refiram os fatos do lançamento extemporâneo, informar a data de "
            "encerramento do exercício em que ocorreram esses fatos."
        ),
    )

    VL_LCTO_MF = fields.Monetary(
        string="Valor do lançamento em moeda funcional",
        xsd_type="TDec_1602",
        currency_field="brl_currency_id",
        help=("Valor do lançamento em moeda funcional, convertido para reais."),
    )

    reg_I200_ids_RegistroI010_id = fields.Many2one(
        comodel_name="l10n_br_sped.ecd.1.I010",
        string="IDENTIFICAÇÃO DA ESCRITURAÇÃO CONTÁBIL",
        required=True,
    )

    reg_I250_ids = fields.One2many(
        "l10n_br_sped.ecd.1.I250",
        "reg_I250_ids_RegistroI200_id",
        string="PARTIDAS DO LANÇAMENTO CONTÁBIL",
    )


class RegistroI250(models.Model):
    "PARTIDAS DO LANÇAMENTO CONTÁBIL"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.I250"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "RegistroI250"

    COD_CTA = fields.Char(
        string="Código da conta analítica debitada/creditada", required=True
    )

    COD_CCUS = fields.Char(string="Código do centro de custos")

    VL_DC = fields.Monetary(
        string="Valor da partida",
        required=True,
        xsd_type="TDec_1602",
        currency_field="brl_currency_id",
    )

    IND_DC = fields.Char(
        string="Indicador da natureza da partida: D",
        required=True,
        help="Indicador da natureza da partida: D - Débito; C - Crédito.",
    )

    NUM_ARQ = fields.Char(
        string="Número",
        help=("Número, Código ou caminho de localização dos documentos " "arquivados."),
    )

    COD_HIST_PAD = fields.Char(
        string="Código do histórico padronizado",
        help="Código do histórico padronizado, conforme tabela I075.",
    )

    HIST = fields.Char(
        string="O Histórico completo da partida ou histórico complementar",
        help=(
            "O Histórico completo da partida ou histórico complementar. "
            "bservação: Caso o lançamento seja do tipo “X” – lançamento "
            "extemporâneo - em qualquer das formas de retificação, o histórico"
            " do lançamento extemporâneo deve especificar o motivo da "
            "correção, a data e o número do lançamento de origem (item 32 do "
            "ITG 2000 (R1))."
        ),
    )

    COD_PART = fields.Char(
        string="PART",
        help=(
            "Código de identificação do participante na partida conforme "
            "tabela 0150 (preencher somente quando identificado o tipo de "
            "participação no registro 0180)."
        ),
    )

    VL_DC_MF = fields.Monetary(
        string="Valor da partida em moeda funcional",
        xsd_type="TDec_1602",
        currency_field="brl_currency_id",
        help="Valor da partida em moeda funcional, convertido para reais.",
    )

    IND_DC_MF = fields.Char(
        string="Indicador da natureza da partida em moeda funcional: D",
        help=(
            "Indicador da natureza da partida em moeda funcional: D - Débito; "
            "C - Crédito."
        ),
    )

    reg_I250_ids_RegistroI200_id = fields.Many2one(
        comodel_name="l10n_br_sped.ecd.1.I200",
        string="LANÇAMENTO CONTÁBIL",
        required=True,
    )


class RegistroI300(models.Model):
    "BALANCETES DIÁRIOS – IDENTIFICAÇÃO DA DATA"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.I300"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "RegistroI300"

    DT_BCTE = fields.Date(string="Data do balancete", required=True)

    reg_I300_ids_RegistroI010_id = fields.Many2one(
        comodel_name="l10n_br_sped.ecd.1.I010",
        string="IDENTIFICAÇÃO DA ESCRITURAÇÃO CONTÁBIL",
        required=True,
    )

    reg_I310_ids = fields.One2many(
        "l10n_br_sped.ecd.1.I310",
        "reg_I310_ids_RegistroI300_id",
        string="DETALHES DO BALANCETE DIÁRIO",
    )


class RegistroI310(models.Model):
    "DETALHES DO BALANCETE DIÁRIO"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.I310"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "RegistroI310"

    COD_CTA = fields.Char(
        string="Código da conta analítica debitada/creditada", required=True
    )

    COD_CCUS = fields.Char(string="Código do centro de custos")

    VAL_DEBD = fields.Monetary(
        string="Total dos débitos do dia",
        required=True,
        xsd_type="TDec_1602",
        currency_field="brl_currency_id",
    )

    VAL_CREDD = fields.Monetary(
        string="Total dos créditos do dia",
        required=True,
        xsd_type="TDec_1602",
        currency_field="brl_currency_id",
    )

    VAL_DEB_MF = fields.Monetary(
        string="Total dos débitos do dia em moeda funcional",
        xsd_type="TDec_1602",
        currency_field="brl_currency_id",
        help=("Total dos débitos do dia em moeda funcional, convertido para " "reais."),
    )

    VAL_CRED_MF = fields.Monetary(
        string="Total dos créditos do dia em moeda funcional",
        xsd_type="TDec_1602",
        currency_field="brl_currency_id",
        help=(
            "Total dos créditos do dia em moeda funcional, convertido para " "reais."
        ),
    )

    reg_I310_ids_RegistroI300_id = fields.Many2one(
        comodel_name="l10n_br_sped.ecd.1.I300",
        string="BALANCETES DIÁRIOS – IDENTIFICAÇÃO DA DATA",
        required=True,
    )


class RegistroI350(models.Model):
    """SALDOS DAS CONTAS DE RESULTADO ANTES DO ENCERRAMENTO – IDENTIFICAÇÃO DA
    DATA"""

    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.I350"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "RegistroI350"

    DT_RES = fields.Date(string="Data da apuração do resultado", required=True)

    reg_I350_ids_RegistroI010_id = fields.Many2one(
        comodel_name="l10n_br_sped.ecd.1.I010",
        string="IDENTIFICAÇÃO DA ESCRITURAÇÃO CONTÁBIL",
        required=True,
    )

    reg_I355_ids = fields.One2many(
        "l10n_br_sped.ecd.1.I355",
        "reg_I355_ids_RegistroI350_id",
        string="ids",
        help=("DOS SALDOS DAS CONTAS DE RESULTADO ANTES DO DETALHES ENCERRAMENTO"),
    )


class RegistroI355(models.Model):
    "DOS SALDOS DAS CONTAS DE RESULTADO ANTES DO DETALHES ENCERRAMENTO"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.I355"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "RegistroI355"

    COD_CTA = fields.Char(
        string="Código da conta analítica de resultado", required=True
    )

    COD_CCUS = fields.Char(string="Código do centro de custos")

    VL_CTA = fields.Monetary(
        string="Valor do saldo final antes do lançamento de encerramento",
        required=True,
        xsd_type="TDec_1602",
        currency_field="brl_currency_id",
    )

    IND_DC = fields.Char(
        string="Indicador da situação do saldo final: D",
        required=True,
        help=("Indicador da situação do saldo final: D - Devedor; C - Credor."),
    )

    VL_CTA_MF = fields.Monetary(
        string="MF",
        xsd_type="TDec_1602",
        currency_field="brl_currency_id",
        help=(
            "Valor do saldo final antes do lançamento de encerramento em moeda"
            " funcional, convertido para reais."
        ),
    )

    IND_DC_MF = fields.Char(
        string="Indicador da situação do saldo final em moeda funcional: D",
        help=(
            "Indicador da situação do saldo final em moeda funcional: D - "
            "Devedor; C - Credor."
        ),
    )

    reg_I355_ids_RegistroI350_id = fields.Many2one(
        comodel_name="l10n_br_sped.ecd.1.I350",
        string="id",
        required=True,
        help=(
            "SALDOS DAS CONTAS DE RESULTADO ANTES DO ENCERRAMENTO – "
            "IDENTIFICAÇÃO DA DATA"
        ),
    )


class RegistroI500(models.Model):
    """PARÂMETROS DE IMPRESSÃO/VISUALIZAÇÃO DO LIVRO RAZÃO AUXILIAR COM LEIAUTE
    PARAMETRIZÁVEL"""

    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.I500"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "RegistroI500"

    TAM_FONTE = fields.Integer(string="Tamanho da fonte", required=True)

    reg_I500_ids_RegistroI010_id = fields.Many2one(
        comodel_name="l10n_br_sped.ecd.1.I010",
        string="IDENTIFICAÇÃO DA ESCRITURAÇÃO CONTÁBIL",
        required=True,
    )


class RegistroI510(models.Model):
    """DEFINIÇÃO DOS CAMPOS DO LIVRO RAZÃO AUXILIAR COM LEIAUTE
    PARAMETRIZÁVEL"""

    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.I510"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "RegistroI510"

    NM_CAMPO = fields.Char(
        string="Nome do campo",
        required=True,
        help="Nome do campo, sem espaços em branco ou caractere especial.",
    )

    DESC_CAMPO = fields.Char(
        string="Descrição do campo",
        required=True,
        help=("Descrição do campo (utilizada na visualização do Livro Auxiliar)"),
    )

    TIPO_CAMPO = fields.Char(
        string="Tipo do campo: “N” – Numérico; “C” – Caractere", required=True
    )

    TAM_CAMPO = fields.Integer(string="Tamanho do campo", required=True)

    DEC_CAMPO = fields.Integer(
        string="Quantidade de casas decimais para campos tipo “N”"
    )

    COL_CAMPO = fields.Integer(
        string="Largura da coluna no relatório",
        required=True,
        help=("Largura da coluna no relatório (em quantidade de caracteres)."),
    )

    reg_I510_ids_RegistroI010_id = fields.Many2one(
        comodel_name="l10n_br_sped.ecd.1.I010",
        string="IDENTIFICAÇÃO DA ESCRITURAÇÃO CONTÁBIL",
        required=True,
    )


class RegistroJ005(models.Model):
    "DEMONSTRAÇÕES CONTÁBEIS"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.J005"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "RegistroJ005"

    DT_INI = fields.Date(
        string="O Data inicial das demonstrações contábeis",
        required=True,
        help=(
            "O Data inicial das demonstrações contábeis. bservação: A data "
            "inicial das demonstrações deve ser a data posterior ao último "
            "encerramento do exercício, mesmo que essa data não esteja no "
            "período da ECD transmitida. Exemplo: Data do Último Encerramento "
            "do Exercício: 31/12/2021 Data Inicial das Demonstrações "
            "Contábeis: 01/01/2022"
        ),
    )

    DT_FIN = fields.Date(string="Data final das demonstrações contábeis", required=True)

    ID_DEM = fields.Integer(
        string="DEM",
        required=True,
        help=(
            "Identificação das demonstrações: 1 – demonstrações contábeis da "
            "pessoa jurídica a que se refere a escrituração (inclusive "
            "Matrix/Filiais); 2 – demonstrações consolidadas ou de outras "
            "pessoas jurídicas."
        ),
    )

    CAB_DEM = fields.Char(string="Cabeçalho das demonstrações")

    reg_J100_ids = fields.One2many(
        "l10n_br_sped.ecd.1.J100",
        "reg_J100_ids_RegistroJ005_id",
        string="BALANÇO PATRIMONIAL",
    )

    reg_J150_ids = fields.One2many(
        "l10n_br_sped.ecd.1.J150",
        "reg_J150_ids_RegistroJ005_id",
        string="DEMONSTRAÇÃO DO RESULTADO DO EXERCÍCIO",
        help="DEMONSTRAÇÃO DO RESULTADO DO EXERCÍCIO (DRE)",
    )

    reg_J210_ids = fields.One2many(
        "l10n_br_sped.ecd.1.J210",
        "reg_J210_ids_RegistroJ005_id",
        string="DE OU DEMONSTRAÇÃO LUCROS PREJUÍZOS ACUMULADOS DO",
        help=(
            "DE OU DEMONSTRAÇÃO LUCROS PREJUÍZOS ACUMULADOS DO "
            "(DLPA)/DEMONSTRAÇÃO DE MUTAÇÕES PATRIMÔNIO LÍQUIDO (DMPL)"
        ),
    )

    reg_J800_ids = fields.One2many(
        "l10n_br_sped.ecd.1.J800",
        "reg_J800_ids_RegistroJ005_id",
        string="OUTRAS INFORMAÇÕES",
    )

    reg_J801_ids = fields.One2many(
        "l10n_br_sped.ecd.1.J801",
        "reg_J801_ids_RegistroJ005_id",
        string="TERMO DE VERIFICAÇÃO PARA FINS DE SUBSTITUIÇÃO DA ECD",
    )


class RegistroJ100(models.Model):
    "BALANÇO PATRIMONIAL"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.J100"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "RegistroJ100"

    COD_AGL = fields.Char(
        string="O Código de aglutinação atribuído pela pessoa jurídica",
        required=True,
        help=(
            "O Código de aglutinação atribuído pela pessoa jurídica. "
            "bservação: Caso o indicador de código de aglutinação seja "
            "totalizador (T), o código de aglutinação deve ser informado, mas "
            "não deve estar cadastrado no registro I052 – os códigos de "
            "aglutinação informados no registro I052 são somente"
        ),
    )

    IND_COD_AGL = fields.Char(
        string="AGL",
        required=True,
        help=(
            "Indicador do tipo de código de aglutinação das linhas: T – "
            "Totalizador (nível que totaliza um ou mais níveis inferiores da "
            "demonstração financeira) D – Detalhe (nível mais detalhado da "
            "demonstração financeira)"
        ),
    )

    NIVEL_AGL = fields.Integer(
        string="Nível do Código de aglutinação",
        required=True,
        help=(
            "Nível do Código de aglutinação (mesmo conceito do plano de contas"
            " – Registro I050)."
        ),
    )

    COD_AGL_SUP = fields.Char(
        string="SUP",
        help=(
            "Código de aglutinação sintético/grupo de código de aglutinação de"
            " nível superior."
        ),
    )

    IND_GRP_BAL = fields.Char(
        string="BAL",
        required=True,
        help=(
            "Indicador de grupo do balanço: A – Ativo; P – Passivo e "
            "Patrimônio Líquido."
        ),
    )

    DESCR_COD_AGL = fields.Char(
        string="Descrição do Código de aglutinação", required=True
    )

    VL_CTA_INI = fields.Monetary(
        string="INI",
        required=True,
        xsd_type="TDec_1602",
        currency_field="brl_currency_id",
        help=(
            "Valor inicial do código de aglutinação no Balanço Patrimonial no "
            "exercício informado, ou de período definido em norma específica."
        ),
    )

    IND_DC_CTA_INI = fields.Char(
        string="INI (IND_DC_CTA_INI)",
        required=True,
        help=(
            "Indicador da situação do saldo inicial informado no campo "
            "anterior: D - Devedor; C – Credor."
        ),
    )

    VL_CTA_FIN = fields.Monetary(
        string="FIN",
        required=True,
        xsd_type="TDec_1602",
        currency_field="brl_currency_id",
        help=(
            "Valor final do código de aglutinação no Balanço Patrimonial no "
            "exercício informado, ou de período definido em norma específica."
        ),
    )

    IND_DC_CTA_FIN = fields.Char(
        string="FIN (IND_DC_CTA_FIN)",
        required=True,
        help=(
            "Indicador da situação do saldo final informado no campo anterior:"
            " D - Devedor; C – Credor."
        ),
    )

    NOTA_EXP_REF = fields.Char(
        string="REF",
        help=(
            "Referência a numeração das notas explicativas relativas às "
            "demonstrações contábeis."
        ),
    )

    reg_J100_ids_RegistroJ005_id = fields.Many2one(
        comodel_name="l10n_br_sped.ecd.1.J005",
        string="DEMONSTRAÇÕES CONTÁBEIS",
        required=True,
    )


class RegistroJ150(models.Model):
    "DEMONSTRAÇÃO DO RESULTADO DO EXERCÍCIO (DRE)"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.J150"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "RegistroJ150"

    NU_ORDEM = fields.Integer(
        string="O Número de ordem da linha na visualização da demonstração",
        required=True,
        help=(
            "O Número de ordem da linha na visualização da demonstração. rdem "
            "de apresentação da linha na visualização do registro J150."
        ),
    )

    COD_AGL = fields.Char(
        string="O Código de aglutinação das linhas",
        help=(
            "O Código de aglutinação das linhas, atribuído pela pessoa "
            "jurídica. bservação: Caso o indicador de código de aglutinação "
            "seja totalizador (T), o código de aglutinação deve ser informado,"
            " mas não deve estar cadastrado no"
        ),
    )

    IND_COD_AGL = fields.Char(
        string="AGL",
        required=True,
        help=(
            "Indicador do tipo de código de aglutinação das linhas: T – "
            "Totalizador (nível que totaliza um ou mais níveis inferiores da "
            "demonstração financeira) D – Detalhe (nível mais detalhado da "
            "demonstração financeira)"
        ),
    )

    NIVEL_AGL = fields.Integer(
        string="Nível do Código de aglutinação",
        required=True,
        help=(
            "Nível do Código de aglutinação (mesmo conceito do plano de contas"
            " – Registro I050)."
        ),
    )

    COD_AGL_SUP = fields.Char(
        string="SUP",
        help=(
            "Código de aglutinação sintético/grupo de código de aglutinação de"
            " nível superior."
        ),
    )

    DESCR_COD_AGL = fields.Char(
        string="Descrição do Código de aglutinação", required=True
    )

    VL_CTA_INI = fields.Monetary(
        string="INI",
        xsd_type="TDec_1602",
        currency_field="brl_currency_id",
        help=(
            "Valor do saldo final da linha no período imediatamente anterior "
            "(saldo final da DRE anterior)."
        ),
    )

    IND_DC_CTA_INI = fields.Char(
        string="INI (IND_DC_CTA_INI)",
        help=(
            "Indicador da situação do valor final da linha no período "
            "imediatamente anterior: D – Devedor; C – Credor."
        ),
    )

    VL_CTA_FIN = fields.Monetary(
        string="Valor final da linha antes do encerramento do exercício",
        required=True,
        xsd_type="TDec_1602",
        currency_field="brl_currency_id",
    )

    IND_DC_CTA_FIN = fields.Char(
        string="FIN",
        required=True,
        help=(
            "Indicador da situação do valor final da linha antes do "
            "encerramento do exercício: D – Devedor; C – Credor."
        ),
    )

    IND_GRP_DRE = fields.Char(
        string="DRE",
        required=True,
        help=(
            "D R Indicador de grupo da DRE: – Linha totalizadora ou de detalhe"
            " da demonstração que, por sua natureza de despesa, represente "
            "redução do lucro. – Linha totalizadora ou de detalhe da "
            "demonstração que, por sua natureza de receita, represente "
            "incremento do lucro."
        ),
    )

    NOTA_EXP_REF = fields.Char(
        string="REF",
        help=(
            "Referência a numeração das notas explicativas relativas às "
            "demonstrações contábeis."
        ),
    )

    reg_J150_ids_RegistroJ005_id = fields.Many2one(
        comodel_name="l10n_br_sped.ecd.1.J005",
        string="DEMONSTRAÇÕES CONTÁBEIS",
        required=True,
    )


class RegistroJ210(models.Model):
    """DE OU DEMONSTRAÇÃO LUCROS PREJUÍZOS ACUMULADOS DO (DLPA)/DEMONSTRAÇÃO DE
    MUTAÇÕES PATRIMÔNIO LÍQUIDO (DMPL)"""

    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.J210"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "RegistroJ210"

    IND_TIP = fields.Integer(
        string="TIP",
        required=True,
        help=(
            "Indicador do tipo de demonstração: 0 – DLPA – Demonstração de "
            "Lucro ou Prejuízos Acumulados 1 – DMPL – Demonstração de Mutações"
            " do Patrimônio Líquido"
        ),
    )

    COD_AGL = fields.Char(
        string="AGL",
        required=True,
        help=(
            "Código de aglutinação das contas analíticas do patrimônio "
            "líquido, atribuído pela empresa."
        ),
    )

    DESCR_COD_AGL = fields.Char(
        string="Descrição do código de aglutinação", required=True
    )

    VL_CTA_INI = fields.Monetary(
        string="INI",
        required=True,
        xsd_type="TDec_1602",
        currency_field="brl_currency_id",
        help=(
            "Saldo inicial do código de aglutinação na demonstração do período"
            " informado."
        ),
    )

    IND_DC_CTA_INI = fields.Char(
        string="INI (IND_DC_CTA_INI)",
        required=True,
        help=(
            "Indicador da situação do saldo inicial informado no campo "
            "anterior: D – Devedor C – Credor"
        ),
    )

    VL_CTA_FIN = fields.Monetary(
        string="FIN",
        required=True,
        xsd_type="TDec_1602",
        currency_field="brl_currency_id",
        help=(
            "Saldo final do código de aglutinação na demonstração do período "
            "informado."
        ),
    )

    IND_DC_CTA_FIN = fields.Char(
        string="FIN (IND_DC_CTA_FIN)",
        required=True,
        help=(
            "Indicador da situação do saldo final informado no campo anterior:"
            " D – Devedor C – Credor"
        ),
    )

    NOTAS_EXP_REF = fields.Char(
        string="REF",
        help=(
            "Referência à numeração das notas explicativas relativas às "
            "demonstrações contábeis."
        ),
    )

    reg_J210_ids_RegistroJ005_id = fields.Many2one(
        comodel_name="l10n_br_sped.ecd.1.J005",
        string="DEMONSTRAÇÕES CONTÁBEIS",
        required=True,
    )

    reg_J215_ids = fields.One2many(
        "l10n_br_sped.ecd.1.J215",
        "reg_J215_ids_RegistroJ210_id",
        string="ids",
        help=(
            "FATO CONTÁBIL QUE ALTERA A CONTA LUCROS ACUMULADOS OU A CONTA "
            "PREJUÍZOS ACUMULADOS OU O PATRIMÔNIO LÍQUIDO"
        ),
    )


class RegistroJ215(models.Model):
    """FATO CONTÁBIL QUE ALTERA A CONTA LUCROS ACUMULADOS OU A CONTA PREJUÍZOS
    ACUMULADOS OU O PATRIMÔNIO LÍQUIDO"""

    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.J215"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "RegistroJ215"

    COD_HIST_FAT = fields.Char(
        string="Código do histórico do fato contábil", required=True
    )

    DESC_FAT = fields.Char(string="Descrição do Fato Contábil", required=True)

    VL_FAT_CONT = fields.Monetary(
        string="Valor do fato contábil",
        required=True,
        xsd_type="TDec_1602",
        currency_field="brl_currency_id",
    )

    IND_DC_FAT = fields.Char(
        string="FAT",
        required=True,
        help=(
            "Indicador de situação do saldo informado no campo anterior: D – "
            "Devedor C – Credor P – Subtotal ou total positivo N – Subtotal ou"
            " total negativo"
        ),
    )

    reg_J215_ids_RegistroJ210_id = fields.Many2one(
        comodel_name="l10n_br_sped.ecd.1.J210",
        string="DE OU DEMONSTRAÇÃO LUCROS PREJUÍZOS ACUMULADOS DO",
        required=True,
        help=(
            "DE OU DEMONSTRAÇÃO LUCROS PREJUÍZOS ACUMULADOS DO "
            "(DLPA)/DEMONSTRAÇÃO DE MUTAÇÕES PATRIMÔNIO LÍQUIDO (DMPL)"
        ),
    )


class RegistroJ800(models.Model):
    "OUTRAS INFORMAÇÕES"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.J800"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "RegistroJ800"

    TIPO_DOC = fields.Char(
        string="DOC",
        required=True,
        help=(
            "Tipo de documento: 001: Demonstração do Resultado Abrangente do "
            "Período 002: Demonstração dos Fluxos de Caixa 003: Demonstração "
            "do Valor Adicionado 010: Notas Explicativas 011: Relatório da "
            "Administração 012: Parecer dos Auditores 099: Outros"
        ),
    )

    DESC_RTF = fields.Char(string="Descrição do arquivo .rtf")

    HASH_RTF = fields.Char(
        string="Hash do arquivo .rtf incluído",
        help=(
            "Hash do arquivo .rtf incluído. Observação: O HASH é preenchido "
            "automaticamente pelo sistema (não é editável e não pode ser "
            "alterado)."
        ),
    )

    ARQ_RTF = fields.Char(
        string="RTF",
        required=True,
        help=(
            "Sequência de bytes que representem um único arquivo no formato "
            "RTF (Rich Text Format)."
        ),
    )

    IND_FIM_RTF = fields.Char(
        string="Indicador de fim do arquivo RTF",
        required=True,
        help=("Indicador de fim do arquivo RTF. Texto fixo contendo “J800FIM”."),
    )

    reg_J800_ids_RegistroJ005_id = fields.Many2one(
        comodel_name="l10n_br_sped.ecd.1.J005",
        string="DEMONSTRAÇÕES CONTÁBEIS",
        required=True,
    )


class RegistroJ801(models.Model):
    "TERMO DE VERIFICAÇÃO PARA FINS DE SUBSTITUIÇÃO DA ECD"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.J801"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "RegistroJ801"

    TIPO_DOC = fields.Char(
        string="DOC",
        required=True,
        help=(
            "Tipo de documento: 001: Termo de Verificação para Fins "
            "Substituição da ECD"
        ),
    )

    DESC_RTF = fields.Char(string="Descrição do arquivo .rtf")

    COD_MOT_SUBS = fields.Char(
        string="SUBS",
        required=True,
        help=(
            "O Código do motivo da substituição: 001 – Mudanças de saldos das "
            "contas que não podem ser realizadas por meio de lançamentos "
            "extemporâneos 002 – Alteração de assinatura 003 – Alteração de "
            "demonstrações contábeis 004 – Alteração da forma de escrituração "
            "contábil 005 – Alteração do número do livro 099 – Outros "
            "bservação: O código a ser adotado deve ser aquele cujo motivo é o"
            " preponderante na substituição da ECD."
        ),
    )

    HASH_RTF = fields.Char(
        string="Hash do arquivo .rtf incluído",
        help=(
            "Hash do arquivo .rtf incluído. Observação: O HASH é preenchido "
            "automaticamente pelo sistema (não é editável e não pode ser "
            "alterado)."
        ),
    )

    ARQ_RTF = fields.Char(
        string="RTF",
        required=True,
        help=(
            "Sequência de bytes que representem um único arquivo no formato "
            "RTF (Rich Text Format)."
        ),
    )

    IND_FIM_RTF = fields.Char(
        string="Indicador de fim do arquivo RTF",
        required=True,
        help=("Indicador de fim do arquivo RTF. Texto fixo contendo “J801FIM”."),
    )

    reg_J801_ids_RegistroJ005_id = fields.Many2one(
        comodel_name="l10n_br_sped.ecd.1.J005",
        string="DEMONSTRAÇÕES CONTÁBEIS",
        required=True,
    )


class RegistroJ900(models.Model):
    "TERMO DE ENCERRAMENTO"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.J900"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "RegistroJ900"

    DNRC_ENCER = fields.Char(
        string="Texto fixo contendo “TERMO DE ENCERRAMENTO”", required=True
    )

    NUM_ORD = fields.Integer(
        string="Número de ordem do instrumento de escrituração", required=True
    )

    NAT_LIVRO = fields.Char(
        string="LIVRO",
        required=True,
        help=("Natureza do livro; finalidade a que se destinou o instrumento."),
    )

    NOME = fields.Char(string="Nome empresarial", required=True)

    QTD_LIN = fields.Integer(
        string="Quantidade total de linhas do arquivo digital", required=True
    )

    DT_INI_ESCR = fields.Date(string="Data de início da escrituração", required=True)

    DT_FIN_ESCR = fields.Date(string="Data de término da escrituração", required=True)

    reg_J930_ids = fields.One2many(
        "l10n_br_sped.ecd.1.J930",
        "reg_J930_ids_RegistroJ900_id",
        string="SIGNATÁRIOS DA ESCRITURAÇÃO",
    )

    reg_J932_ids = fields.One2many(
        "l10n_br_sped.ecd.1.J932",
        "reg_J932_ids_RegistroJ900_id",
        string="ids",
        help=(
            "SIGNATÁRIOS DO TERMO DE VERIFICAÇÃO PARA FINS DE SUBSTITUIÇÃO DA " "ECD"
        ),
    )

    reg_J935_ids = fields.One2many(
        "l10n_br_sped.ecd.1.J935",
        "reg_J935_ids_RegistroJ900_id",
        string="IDENTIFICAÇÃO DOS AUDITORES INDEPENDENTES",
    )


class RegistroJ930(models.Model):
    "SIGNATÁRIOS DA ESCRITURAÇÃO"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.J930"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "RegistroJ930"

    IDENT_NOM = fields.Char(string="Nome do signatário", required=True)

    IDENT_CPF_CNPJ = fields.Integer(string="CPF ou CNPJ", required=True)

    IDENT_QUALIF = fields.Char(
        string="Qualificação do assinante",
        required=True,
        help="Qualificação do assinante, conforme tabela.",
    )

    COD_ASSIN = fields.Char(
        string="Código de qualificação do assinante",
        required=True,
        help="Código de qualificação do assinante, conforme tabela.",
    )

    IND_CRC = fields.Char(
        string="CRC",
        help=(
            "Número de inscrição do contabilista no Conselho Regional de "
            "Contabilidade."
        ),
    )

    EMAIL = fields.Char(string="Email do signatário")

    FONE = fields.Char(string="Telefone do signatário")

    UF_CRC = fields.Char(string="Indicação da unidade da federação que expediu o CRC")

    NUM_SEQ_CRC = fields.Char(
        string="CRC (NUM_SEQ_CRC)",
        help=(
            "Número da Certidão de Regularidade Profissional do Contador no "
            "seguinte formato: UF/ano/número"
        ),
    )

    DT_CRC = fields.Date(
        string="CRC (DT_CRC)",
        help=(
            "Data de validade da Certidão de Regularidade Profissional do " "Contador"
        ),
    )

    IND_RESP_LEGAL = fields.Char(
        string="LEGAL",
        required=True,
        help=(
            "Identificação do signatário que será validado como responsável "
            "pela assinatura da ECD, conforme atos societários: S – Sim N – "
            "Não"
        ),
    )

    reg_J930_ids_RegistroJ900_id = fields.Many2one(
        comodel_name="l10n_br_sped.ecd.1.J900",
        string="TERMO DE ENCERRAMENTO",
        required=True,
    )


class RegistroJ932(models.Model):
    """SIGNATÁRIOS DO TERMO DE VERIFICAÇÃO PARA FINS DE SUBSTITUIÇÃO DA ECD"""

    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.J932"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "RegistroJ932"

    IDENT_NOM_T = fields.Char(
        string="Nome do signatário do termo de verificação", required=True
    )

    IDENT_CPF_CNPJ_T = fields.Integer(
        string="CPF ou CNPJ do assinante do termo de verificação", required=True
    )

    IDENT_QUALIF_T = fields.Char(
        string="Qualificação do assinante do termo de verificação",
        required=True,
        help=("Qualificação do assinante do termo de verificação, conforme " "tabela."),
    )

    COD_ASSIN_T = fields.Char(
        string="T",
        required=True,
        help=(
            "Código de qualificação do assinante do termo de verificação, "
            "conforme tabela."
        ),
    )

    IND_CRC_T = fields.Char(string="Número de inscrição do contabilista no Conselho")

    EMAIL_T = fields.Char(string="Email do signatário")

    FONE_T = fields.Char(string="Telefone do signatário")

    UF_CRC_T = fields.Char(string="Indicação da unidade da federação que expediu o CRC")

    NUM_SEQ_CRC_T = fields.Char(
        string="T (NUM_SEQ_CRC_T)",
        help=(
            "Número da Certidão de Regularidade Profissional do Contador no "
            "seguinte formato: UF/ano/número"
        ),
    )

    DT_CRC_T = fields.Date(
        string="T (DT_CRC_T)",
        help=(
            "Data de validade da Certidão de Regularidade Profissional do " "Contador"
        ),
    )

    reg_J932_ids_RegistroJ900_id = fields.Many2one(
        comodel_name="l10n_br_sped.ecd.1.J900",
        string="TERMO DE ENCERRAMENTO",
        required=True,
    )


class RegistroJ935(models.Model):
    "IDENTIFICAÇÃO DOS AUDITORES INDEPENDENTES"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.J935"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "RegistroJ935"

    NI_CPF_CNPJ = fields.Char(
        string="CNPJ",
        required=True,
        help=(
            "CPF do auditor independente/CNPJ da pessoa jurídica de auditoria "
            "independente."
        ),
    )

    NOME_AUDITOR_FIRMA = fields.Char(
        string="FIRMA",
        required=True,
        help=(
            "Nome do auditor independente ou pessoa jurídica de auditoria "
            "independente."
        ),
    )

    COD_CVM_AUDITOR = fields.Char(string="Registro do auditor independente na CVM")

    reg_J935_ids_RegistroJ900_id = fields.Many2one(
        comodel_name="l10n_br_sped.ecd.1.J900",
        string="TERMO DE ENCERRAMENTO",
        required=True,
    )


class RegistroK030(models.Model):
    "PERÍODO DA ESCRITURAÇÃO CONTÁBIL CONSOLIDADA"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.K030"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "RegistroK030"

    DT_INI = fields.Date(string="Data inicial do período consolidado", required=True)

    DT_FIN = fields.Date(string="Data final do período consolidado", required=True)

    reg_K100_ids = fields.One2many(
        "l10n_br_sped.ecd.1.K100",
        "reg_K100_ids_RegistroK030_id",
        string="RELAÇÃO DAS EMPRESAS CONSOLIDADAS",
    )


class RegistroK100(models.Model):
    "RELAÇÃO DAS EMPRESAS CONSOLIDADAS"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.K100"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "RegistroK100"

    COD_PAIS = fields.Integer(
        string="Código do país da empresa",
        required=True,
        help=(
            "Código do país da empresa, conforme tabela do Banco Central do " "Brasil."
        ),
    )

    EMP_COD = fields.Integer(
        string="Código de identificação da empresa participante", required=True
    )

    CNPJ = fields.Integer(string="CNPJ", help="CNPJ (somente os 8 primeiros dígitos).")

    NOME = fields.Char(string="Nome empresarial", required=True)

    PER_PART = fields.Float(
        string="PART",
        required=True,
        xsd_type="TDec_1604",
        digits=(
            16,
            4,
        ),
        help=(
            "Percentual de participação total do conglomerado na empresa no "
            "final do período consolidado. Observação: Neste campo, deve ser "
            "informado o percentual de participação acionária da empresa "
            "titular da ECD."
        ),
    )

    EVENTO = fields.Char(
        string="Evento societário ocorrido no período: S",
        required=True,
        help="Evento societário ocorrido no período: S - Sim N – Não",
    )

    PER_CONS = fields.Float(
        string="CONS",
        required=True,
        xsd_type="TDec_1604",
        digits=(
            16,
            4,
        ),
        help=(
            "Percentual de consolidação da empresa no final do período "
            "consolidado: Informar o percentual do resultado da empresa que "
            "foi para a consolidação."
        ),
    )

    DATA_INI_EMP = fields.Char(
        string="EMP",
        required=True,
        help=(
            "Data inicial do período da escrituração contábil da empresa que "
            "foi consolidada."
        ),
    )

    DATA_FIN_EMP = fields.Char(
        string="EMP (DATA_FIN_EMP)",
        required=True,
        help=(
            "Data final do período da escrituração contábil da empresa que foi"
            " consolidada"
        ),
    )

    reg_K100_ids_RegistroK030_id = fields.Many2one(
        comodel_name="l10n_br_sped.ecd.1.K030",
        string="PERÍODO DA ESCRITURAÇÃO CONTÁBIL CONSOLIDADA",
        required=True,
    )

    reg_K110_ids = fields.One2many(
        "l10n_br_sped.ecd.1.K110",
        "reg_K110_ids_RegistroK100_id",
        string="RELAÇÃO DOS EVENTOS SOCIETÁRIOS",
    )


class RegistroK110(models.Model):
    "RELAÇÃO DOS EVENTOS SOCIETÁRIOS"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.K110"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "RegistroK110"

    EVENTO = fields.Integer(
        string="EVENTO",
        required=True,
        help=(
            "Evento societário ocorrido no período: 1 – Aquisição 2 – "
            "Alienação 3 – Fusão 4 – Cisão Parcial 5 – Cisão Total 6 – "
            "Incorporação 7 – Extinção 8 – Constituição"
        ),
    )

    DT_EVENTO = fields.Date(string="Data do evento societário", required=True)

    reg_K110_ids_RegistroK100_id = fields.Many2one(
        comodel_name="l10n_br_sped.ecd.1.K100",
        string="RELAÇÃO DAS EMPRESAS CONSOLIDADAS",
        required=True,
    )

    reg_K115_ids = fields.One2many(
        "l10n_br_sped.ecd.1.K115",
        "reg_K115_ids_RegistroK110_id",
        string="EMPRESAS PARTICIPANTES DO EVENTO SOCIETÁRIO",
    )


class RegistroK115(models.Model):
    "EMPRESAS PARTICIPANTES DO EVENTO SOCIETÁRIO"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.K115"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "RegistroK115"

    EMP_COD_PART = fields.Integer(
        string="Código da empresa envolvida na operação", required=True
    )

    COND_PART = fields.Integer(
        string="PART",
        required=True,
        help=(
            "Condição da empresa relacionada à operação: 1 – Sucessora; 2 – "
            "Adquirente; 3 – Alienante."
        ),
    )

    PER_EVT = fields.Float(
        string="Percentual da empresa participante envolvida na operação",
        required=True,
        xsd_type="TDec_1604",
        digits=(
            16,
            4,
        ),
    )

    reg_K115_ids_RegistroK110_id = fields.Many2one(
        comodel_name="l10n_br_sped.ecd.1.K110",
        string="RELAÇÃO DOS EVENTOS SOCIETÁRIOS",
        required=True,
    )


class RegistroK200(models.Model):
    "PLANO DE CONTAS CONSOLIDADO"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.K200"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "RegistroK200"

    COD_NAT = fields.Char(
        string="Código da natureza da conta/grupo de contas",
        required=True,
        help=(
            "Código da natureza da conta/grupo de contas, conforme tabela "
            "publicada pelo Sped."
        ),
    )

    IND_CTA = fields.Char(
        string="Indicador do tipo de conta: S",
        required=True,
        help=(
            "Indicador do tipo de conta: S - Sintética (grupo de contas); A - "
            "Analítica (conta)."
        ),
    )

    NIVEL = fields.Integer(string="Nível da conta", required=True)

    COD_CTA = fields.Char(string="Código da conta", required=True)

    COD_CTA_SUP = fields.Char(string="Código da conta superior")

    CTA = fields.Char(string="Nome da conta", required=True)

    reg_K210_ids = fields.One2many(
        "l10n_br_sped.ecd.1.K210",
        "reg_K210_ids_RegistroK200_id",
        string="ids",
        help="MAPEAMENTO PARA O PLANO DE CONTAS DAS EMPRESAS CONSOLIDADAS",
    )

    reg_K300_ids = fields.One2many(
        "l10n_br_sped.ecd.1.K300",
        "reg_K300_ids_RegistroK200_id",
        string="SALDOS DAS CONTAS CONSOLIDADAS",
    )


class RegistroK210(models.Model):
    "MAPEAMENTO PARA O PLANO DE CONTAS DAS EMPRESAS CONSOLIDADAS"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.K210"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "RegistroK210"

    COD_EMP = fields.Integer(
        string="Código de identificação da empresa participante", required=True
    )

    COD_CTA_EMP = fields.Char(
        string="Código da conta da empresa participante", required=True
    )

    reg_K210_ids_RegistroK200_id = fields.Many2one(
        comodel_name="l10n_br_sped.ecd.1.K200",
        string="PLANO DE CONTAS CONSOLIDADO",
        required=True,
    )


class RegistroK300(models.Model):
    "SALDOS DAS CONTAS CONSOLIDADAS"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.K300"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "RegistroK300"

    COD_CTA = fields.Char(string="Código da conta consolidada", required=True)

    VAL_AG = fields.Monetary(
        string="Valor absoluto aglutinado",
        required=True,
        xsd_type="TDec_1602",
        currency_field="brl_currency_id",
    )

    IND_VAL_AG = fields.Char(
        string="AG",
        required=True,
        help=("Indicador da situação do valor aglutinado: D – Devedor C – Credor"),
    )

    VAL_EL = fields.Monetary(
        string="Valor absoluto das eliminações",
        required=True,
        xsd_type="TDec_1602",
        currency_field="brl_currency_id",
    )

    IND_VAL_EL = fields.Char(
        string="EL",
        required=True,
        help=("Indicador da situação do valor eliminado: D – Devedor C – Credor"),
    )

    VAL_CS = fields.Monetary(
        string="Valor absoluto consolidado: VAL_CS = VAL_AG – VAL_EL",
        required=True,
        xsd_type="TDec_1602",
        currency_field="brl_currency_id",
    )

    IND_VAL_CS = fields.Char(
        string="CS",
        required=True,
        help=("Indicador da situação do valor consolidado: D – Devedor C – " "Credor"),
    )

    reg_K300_ids_RegistroK200_id = fields.Many2one(
        comodel_name="l10n_br_sped.ecd.1.K200",
        string="PLANO DE CONTAS CONSOLIDADO",
        required=True,
    )

    reg_K310_ids = fields.One2many(
        "l10n_br_sped.ecd.1.K310",
        "reg_K310_ids_RegistroK300_id",
        string="EMPRESAS DETENTORAS DAS PARCELAS DO VALOR ELIMINADO TOTAL",
    )


class RegistroK310(models.Model):
    "EMPRESAS DETENTORAS DAS PARCELAS DO VALOR ELIMINADO TOTAL"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.K310"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "RegistroK310"

    EMP_COD_PARTE = fields.Integer(
        string="PARTE",
        required=True,
        help=("Código da empresa detentora do valor aglutinado que foi eliminado"),
    )

    VALOR = fields.Monetary(
        string="Parcela do valor eliminado total",
        required=True,
        xsd_type="TDec_1602",
        currency_field="brl_currency_id",
    )

    IND_VALOR = fields.Char(
        string="VALOR",
        required=True,
        help=("Indicador da situação do valor eliminado: D – Devedor C – Credor"),
    )

    reg_K310_ids_RegistroK300_id = fields.Many2one(
        comodel_name="l10n_br_sped.ecd.1.K300",
        string="SALDOS DAS CONTAS CONSOLIDADAS",
        required=True,
    )

    reg_K315_ids = fields.One2many(
        "l10n_br_sped.ecd.1.K315",
        "reg_K315_ids_RegistroK310_id",
        string="ids",
        help="EMPRESAS CONTRAPARTES DAS PARCELAS DO VALOR ELIMINADO TOTAL",
    )


class RegistroK315(models.Model):
    "EMPRESAS CONTRAPARTES DAS PARCELAS DO VALOR ELIMINADO TOTAL"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.K315"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "RegistroK315"

    EMP_COD_CONTRA = fields.Integer(
        string="Código da empresa da contrapartida", required=True
    )

    COD_CONTRA = fields.Char(
        string="Código da conta consolidada da contrapartida", required=True
    )

    VALOR = fields.Monetary(
        string="Parcela da contrapartida do valor eliminado total",
        required=True,
        xsd_type="TDec_1602",
        currency_field="brl_currency_id",
    )

    IND_VALOR = fields.Char(
        string="VALOR",
        required=True,
        help=("Indicador da situação do valor eliminado: D – Devedor C – Credor"),
    )

    reg_K315_ids_RegistroK310_id = fields.Many2one(
        comodel_name="l10n_br_sped.ecd.1.K310",
        string="EMPRESAS DETENTORAS DAS PARCELAS DO VALOR ELIMINADO TOTAL",
        required=True,
    )


class Registro9900(models.Model):
    "REGISTROS DO ARQUIVO"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "l10n_br_sped.ecd.1.9900"
    _inherit = "l10n_br_sped.mixin"
    _binding_type = "Registro9900"

    REG_BLC = fields.Char(
        string="Registro que será totalizado no próximo campo", required=True
    )

    QTD_REG_BLC = fields.Integer(
        string="Total de registros do tipo informado no campo anterior", required=True
    )
