sudo: false
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev # provides unbuffer utility

language: python

stages:
  - linting
  - test

python:
  - "3.6"

jobs:
  include:
    - stage: linting
      name: "Pre-Commit"
      python: 3.6
      install: pip install pre_commit
      script: pre-commit run --all
env:
  global:
    - VERSION="12.0" TESTS="1" LINT_CHECK="0" MQT_DEP="PIP"

  matrix:
    - ODOO_REPO="odoo/odoo"
    - ODOO_REPO="OCA/OCB"
    - UNIT_TEST="1" ODOO_REPO="OCA/OCB"

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git
    ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - export PATH=.travis:${PATH}

script:
  - travis_run_tests
